import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased op`}>
        <Providers>{children}</Providers>
        <Toaster toastOptions={{ descriptionClassName: '!text-gray-800' }} />
      </body>
    </html>
  );
}
